# Generated by Django 4.2.10 on 2025-11-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='imagen_url',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='medicamentos/'),
        ),
    ]
