# Generated by Django 4.2.10 on 2025-11-19 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_factura_id_factura'),
        ('pedidos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='factura',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido', to='facturacion.factura'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
