# Generated by Django 4.2.10 on 2025-11-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_direccion_usuario_calle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='calle',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='numero',
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion_completa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
